#!/usr/bin/env node
// Render the opener-variety MEASUREMENT report from .deai/openers-summary.json
// (written by classify.mjs). This is the "measure first" deliverable: the whole-book
// opener distribution, which chapters trip the monotony budget, and the worst runs.
// It writes NOTHING to Drive and proposes NO fixes — it tells you WHERE to look.
//
//   node tally.mjs            # terminal report
//   node tally.mjs --md       # emit the markdown block for OPENERS-PASS.md
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const deai = join(here, '..', '..', '..', '.deai')
const MD = process.argv.includes('--md')

let s
try { s = JSON.parse(readFileSync(join(deai, 'openers-summary.json'), 'utf8')) } catch {
  console.error('No .deai/openers-summary.json. Run: node .claude/skills/openers/classify.mjs'); process.exit(1)
}
const tax = JSON.parse(readFileSync(join(here, 'taxonomy.json'), 'utf8'))
const order = ['S', 'P', 'G', 'A', 'C', 'J', 'I', 'D', 'F']
const pct = (n, d) => d ? (100 * n / d).toFixed(1) + '%' : '0%'

// keep chapters in manuscript order; drop front matter / part dividers w/ tiny counts
const chapters = s.chapters.filter(c => c.total >= 8)

if (MD) {
  const L = []
  L.push(`<!-- generated by tally.mjs from classify.mjs — do not hand-edit -->`)
  L.push(`**Whole-book opener distribution** (${s.sentences.toLocaleString()} sentences):\n`)
  L.push('| class | | count | share |')
  L.push('|---|---|--:|--:|')
  for (const c of order) if (s.totals[c]) L.push(`| \`${c}\` | ${tax.classes[c].label} | ${s.totals[c]} | ${pct(s.totals[c], s.sentences)} |`)
  L.push(`\n**Bare subject-led share: ${pct(s.totals.S, s.sentences)}** · varied-opener share: ${pct(order.filter(c => tax.classes[c].varied && c !== 'D' && c !== 'F').reduce((a, c) => a + (s.totals[c] || 0), 0), s.sentences)} · ${s.runsTotal} monotony runs · ${s.flagged} flagged sentences.\n`)
  L.push(`**Chapters over the ${(tax.budgets.pctS_max * 100).toFixed(0)}% subject-led budget:**\n`)
  L.push('| chapter | sentences | %S | %varied | flag |')
  L.push('|---|--:|--:|--:|:--:|')
  for (const c of chapters) L.push(`| ${c.chapter} | ${c.total} | ${pct(c.codes.S || 0, c.total)} | ${pct(Math.round(c.pctVaried * c.total), c.total)} | ${c.overBudget ? '⚠️' : ''} |`)
  L.push(`\n**Ten worst runs:**\n`)
  for (const r of s.worstRuns.slice(0, 10)) L.push(`- **p${r.page} · ${r.chapter} · ${r.len}×${r.code}** — ${r.openers}`)
  console.log(L.join('\n'))
  process.exit(0)
}

// ---- terminal ----
const bar = (frac, w = 24) => '█'.repeat(Math.round(frac * w)).padEnd(w, '·')
console.log(`\n  OPENER-VARIETY REPORT  ·  ${s.sentences.toLocaleString()} sentences\n  ${'─'.repeat(52)}`)
for (const c of order) if (s.totals[c]) {
  const f = s.totals[c] / s.sentences
  console.log(`  ${c}  ${tax.classes[c].label.padEnd(15)} ${String(s.totals[c]).padStart(5)}  ${pct(s.totals[c], s.sentences).padStart(6)}  ${bar(f)}`)
}
const variedShare = order.filter(c => tax.classes[c].varied && c !== 'D' && c !== 'F').reduce((a, c) => a + (s.totals[c] || 0), 0)
console.log(`  ${'─'.repeat(52)}`)
console.log(`  bare subject-led: ${pct(s.totals.S, s.sentences)}   varied openers: ${pct(variedShare, s.sentences)}`)
console.log(`  ${s.runsTotal} monotony runs (>=${s.budgets.typeRun_min})   ${s.flagged} flagged sentences\n`)

const over = chapters.filter(c => c.overBudget)
console.log(`  CHAPTERS OVER ${(s.budgets.pctS_max * 100).toFixed(0)}% SUBJECT-LED  (${over.length} of ${chapters.length})`)
console.log(`  ${'─'.repeat(52)}`)
for (const c of chapters) {
  const flag = c.overBudget ? '⚠️ ' : '   '
  console.log(`  ${flag}${c.chapter.padEnd(22)} ${String(c.total).padStart(4)}  %S ${pct(c.codes.S || 0, c.total).padStart(6)}  ${bar((c.codes.S || 0) / c.total, 16)}`)
}
console.log(`\n  TEN WORST RUNS`)
console.log(`  ${'─'.repeat(52)}`)
for (const r of s.worstRuns.slice(0, 10)) {
  console.log(`  p${String(r.page).padStart(3)} · ${r.len}×${r.code} · ${r.chapter}`)
  console.log(`      ${r.openers}`)
}
console.log(`\n  review queue:  http://localhost:3000/openers`)
console.log(`  paste-ready:   node .claude/skills/openers/tally.mjs --md\n`)
